### ISSUE TITLE
Special characters letters aren't supported

### ISSUE THREAD

**Issue by Zenrac** [TheTrain2000/async2rewrite#2]
I got the following traceback : 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Zenrac\AppData\Local\Programs\Python\Python35\lib\site-packages\async2rewrite\main.py", line 47, in from_file
    code = f.read()
  File "C:\Users\Zenrac\AppData\Local\Programs\Python\Python35\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 101238: character maps to <undefined>
```

**Comment by tylergibbs2** [comment]
Please include your code that you believe to be causing the problem.

**Comment by Zenrac** [comment]
Just noticed my mistake, here's my quick example : 
The following chars cannot be decoded : ɐqɔpǝɟƃɥᴉɾʞlɯuodbɹsʇnʌʍxʎz
But i'm getting some others errors, i'm looking for the source

**Comment by tylergibbs2** [comment]
This issue is fixed in commit https://github.com/TheTrain2000/async2rewrite/commit/79d4418936a3390b6ef0da3fc0dcc7a9b802de84.
